[server]
headless = true
port = $PORT
enableCORS = false
[theme]
primaryColor = "#FF69B4"             
backgroundColor = "#FFFFFF"          
secondaryBackgroundColor = "#FFB6C1" 
textColor = "#4B0082"                
font = "monospace"
