# .streamlit/secrets.toml
[api_credentials]
OPENAI_API_KEY = "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"